services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Icedev\SimpleMessageTransport\Sender\Sender: ~
    Icedev\SimpleMessageTransport\Sender\MessageHandler: ~
    Icedev\SimpleMessageTransport\Sender\MessageApiHandler: ~
